import sqlite3


def execute_query(db_path, sql):
    conn = sqlite3.connect(db_path)

    try:
        cursor = conn.cursor()
        cursor.execute(sql)
        return cursor.fetchall()

    finally:
        conn.close()


def normalize(rows):
    return sorted(rows)


def score_sql(generated_sql, expected_sql, db_path, order_matters=False):
    # First execute the expected SQL
    try:
        expected_result = execute_query(db_path, expected_sql)

    except Exception as e:
        return {
            "correct": False,
            "status": "reference_error",
            "generated_result": None,
            "expected_result": None,
            "error": str(e)
        }

    # Then execute the SQL generated by the model
    try:
        generated_result = execute_query(db_path, generated_sql)

    except sqlite3.OperationalError as e:
        error_message = str(e)

        # Simple distinction for SQLite errors
        if "syntax error" in error_message.lower():
            status = "syntax_error"
        else:
            status = "execution_error"

        return {
            "correct": False,
            "status": status,
            "generated_result": None,
            "expected_result": expected_result,
            "error": error_message
        }

    except Exception as e:
        return {
            "correct": False,
            "status": "execution_error",
            "generated_result": None,
            "expected_result": expected_result,
            "error": str(e)
        }

    # Compare both query results
    if order_matters:
        correct = generated_result == expected_result
    else:
        correct = normalize(generated_result) == normalize(expected_result)

    if correct:
        status = "correct"
    else:
        status = "wrong_result"

    return {
        "correct": correct,
        "status": status,
        "generated_result": generated_result,
        "expected_result": expected_result,
        "error": None
    }